services:
  requisador-dev:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./tailwind.config.js:/app/tailwind.config.js
      - ./package.json:/app/package.json
      # Mount the node_modules as a volume for better performance
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    command: sh -c "npm run build:css:watch & python3 -m http.server 8000 --directory src"
    stdin_open: true
    tty: true

  # Service to run npm commands
  npm:
    build: .
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    working_dir: /app
    command: npm install
    profiles:
      - tools

  # Optional: Production build service
  requisador-prod:
    build: .
    ports:
      - "8001:8000"
    volumes:
      - ./dist:/app/dist
    environment:
      - NODE_ENV=production
    command: sh -c "npm run build && python3 -m http.server 8000 --directory dist"
    profiles:
      - production

volumes:
  node_modules:
