version: '3.8'

services:
  app:
    build: .
    ports:
      - "4200:4200"
    volumes:
      - ./src:/app/src
      - ./dist:/app/dist
      - ./angular.json:/app/angular.json
      - /app/node_modules
